SELECT
 GU.[USERCODE] -- inloggroepen
,GL.[GROEPCODE], G.[MEMO], G.[OMSCHR]
FROM     [dbo].[ZISCON_GROEPUSR] GU
    JOIN [dbo].[ZISCON_GROEPLNK] GL ON GU.[GRPUSRCODE] = GL.[LINKCODE]
    JOIN [dbo].[ZISCON_GROEPEN]  G  ON GL.[GROEPCODE] = G.[CODE]
WHERE  GU.[USERCODE] = 'MPELSMA'

SELECT
 GL.[LINKCODE] -- groepen
,GL.[GROEPCODE], G.[MEMO], G.[OMSCHR]
FROM     [dbo].[ZISCON_GROEPLNK] GL
    JOIN [dbo].[ZISCON_GROEPEN]  G  ON GL.[GROEPCODE] = G.[CODE]
WHERE GL.[linkcode] = 'MPELSMA'

SELECT
 GU.[USERCODE], GU.[GRPUSRCODE]
,GL.[GROEPCODE], G.[MEMO], G.[OMSCHR]
FROM     [dbo].[ZISCON_GROEPUSR] GU
    JOIN [dbo].[ZISCON_GROEPLNK] GL ON ((GU.[GRPUSRCODE] = GL.[LINKCODE]) OR (GU.[USERCODE]) = GL.[LINKCODE])
    JOIN [dbo].[ZISCON_GROEPEN]  G  ON GL.[GROEPCODE] = G.[CODE]
WHERE  GU.[USERCODE] = 'MEGGINK2'